import { Box, ChakraProvider, Flex, HStack, Spinner, Text } from "@chakra-ui/react";
import React from "react";
import ReactDOM from "react-dom/client";
import Dashboard from "./Dashboard";
import Diagnostics from "./Diagnostics";
import Tables from "./Tables";
import { useCampaignData, useViewState } from "./data";
import theme from "../theme";
import { INK, MUTED } from "./ui";

function Page() {
  const { data, error } = useCampaignData();
  const [view, setView] = useViewState();

  if (error) {
    return (
      <Flex minH="60vh" align="center" justify="center" direction="column" gap={2} px={6}>
        <Text fontWeight={700} color={INK}>Couldn't load the campaign data.</Text>
        <Text fontSize="14px" color={MUTED} fontFamily="mono">{error}</Text>
      </Flex>
    );
  }
  if (!data) {
    return (
      <Flex minH="60vh" align="center" justify="center" gap={3}>
        <Spinner size="sm" color="gray.400" />
        <Text fontSize="14px" color={MUTED}>Loading campaign data…</Text>
      </Flex>
    );
  }

  const { meta } = data;
  const flight = `${new Date(`${meta.flightStart}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" })} – ${new Date(`${meta.flightEnd}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`;

  return (
    <Box bg="gray.50" minH="100vh">
      <Box maxW="1280px" mx="auto" px={{ base: 5, md: 8 }} pb={24}>
        {/* masthead */}
        <Box pt={{ base: 10, md: 14 }} pb={5} borderBottom="2px solid" borderColor={INK} mb={5}>
          <HStack spacing={3} mb={4} wrap="wrap"
            fontFamily="mono" fontSize="10.5px" letterSpacing="0.15em"
            textTransform="uppercase" color={MUTED}>
            <Text>Channel performance</Text>
            <Text color="gray.300">/</Text>
            <Text>Synthetic demo data</Text>
            <Text color="gray.300">/</Text>
            <Text>{flight}</Text>
          </HStack>
          <Text as="h1" fontSize={{ base: "30px", md: "44px" }} fontWeight={800}
            letterSpacing="-0.032em" lineHeight={1.05} color={INK} maxW="20ch" mb={3}>
            Which channel should get the next dollar?
          </Text>
          <Text fontSize={{ base: "15px", md: "17px" }} color="gray.600" maxW="72ch">
            {meta.advertiser} — {meta.descriptor}. Display, online video and email, compared on a
            currency that works across all three. Every number here is fabricated for demonstration;
            the published benchmarks they're modelled on are listed at the bottom.
          </Text>
        </Box>

        <Dashboard
          data={data}
          attr={view.attr}
          channel={view.channel}
          setView={setView}
        />
        <Diagnostics data={data} />
        <Tables
          data={data}
          channel={view.channel}
          setChannel={(c) => setView({ channel: c })}
        />

        {/* footer */}
        <Box mt={16} pt={5} borderTop="2px solid" borderColor={INK}>
          <Text fontFamily="mono" fontSize="11px" color={MUTED} lineHeight={1.8}>
            Synthetic demonstration data for a fictional advertiser. No real advertiser, publisher or
            campaign data appears on this page. Modelled on published 2026 benchmarks:
          </Text>
          <Box as="ul" pl={5} mt={2} fontFamily="mono" fontSize="11px" color={MUTED} lineHeight={1.8}>
            {meta.sources.map((s) => <li key={s}>{s}</li>)}
          </Box>
          <Text fontFamily="mono" fontSize="11px" color={MUTED} mt={3}>
            Data generated by <code>scripts/generate_madhive_data.py</code> →{" "}
            <code>public/data/madhive-campaign.json</code>, fetched at runtime. Built with React,
            TypeScript, Chakra UI and Recharts. · Sharon Kwong
          </Text>
        </Box>
      </Box>
    </Box>
  );
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <ChakraProvider theme={theme}>
      <Page />
    </ChakraProvider>
  </React.StrictMode>
);
