import { Box, ChakraProvider, Flex, HStack, Spinner, Text } from "@chakra-ui/react";
import React from "react";
import ReactDOM from "react-dom/client";
import Dashboard from "./Dashboard";
import Diagnostics from "./Diagnostics";
import Tables from "./Tables";
import { CreativeRanking } from "./Creatives";
import { useCampaignData, useViewState } from "./data";
import theme from "../theme";
import { INK, MUTED } from "./ui";

function Page() {
  const { data, error } = useCampaignData();
  const [view, setView] = useViewState();

  if (error) {
    return (
      <Flex minH="60vh" align="center" justify="center" direction="column" gap={2} px={6}>
        <Text fontWeight={700} color={INK}>Couldn't load the campaign data.</Text>
        <Text fontSize="14px" color={MUTED} fontFamily="mono">{error}</Text>
      </Flex>
    );
  }
  if (!data) {
    return (
      <Flex minH="60vh" align="center" justify="center" gap={3}>
        <Spinner size="sm" color="gray.400" />
        <Text fontSize="14px" color={MUTED}>Loading campaign data…</Text>
      </Flex>
    );
  }

  const { meta } = data;
  const flight = `${new Date(`${meta.flightStart}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" })} – ${new Date(`${meta.flightEnd}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`;

  return (
    <Box bg="gray.50" minH="100vh">
      <Box maxW="1280px" mx="auto" px={{ base: 5, md: 8 }} pb={24}>
        {/* masthead */}
        <Box pt={{ base: 10, md: 14 }} pb={5} borderBottom="2px solid" borderColor={INK} mb={5}>
          <Flex justify="space-between" align="baseline" gap={4} wrap="wrap" mb={3}>
            <Text fontSize={{ base: "22px", md: "27px" }} fontWeight={700}
              letterSpacing="-0.02em" color={INK}>
              {meta.advertiser}
            </Text>
            <HStack spacing={3} wrap="wrap" fontFamily="mono" fontSize="10.5px"
              letterSpacing="0.13em" textTransform="uppercase" color={MUTED}>
              <Text>{meta.descriptor}</Text>
              <Text color="gray.300">/</Text>
              <Text>{flight}</Text>
              <Text color="gray.300">/</Text>
              <Text>Demo data</Text>
            </HStack>
          </Flex>
          <Text as="h1" fontSize={{ base: "30px", md: "44px" }} fontWeight={800}
            letterSpacing="-0.032em" lineHeight={1.05} color={INK} maxW="20ch" mb={3}>
Which ads are actually selling pizza?
          </Text>
          <Text fontSize={{ base: "15px", md: "17px" }} color="gray.600" maxW="60ch">
Display, online video and email for a six-shop pizza chain — orders online, visits
            in store, how much of it the advertising actually caused, and where the next dollar
            should go.
          </Text>
        </Box>

        <Dashboard
          data={data}
          channel={view.channel}
          setChannel={(c) => setView({ channel: c })}
        />
        <Diagnostics data={data} />
        <CreativeRanking data={data} />
        <Tables data={data} />

        {/* footer */}
        <Box mt={16} pt={5} borderTop="2px solid" borderColor={INK}>
          <Text fontFamily="mono" fontSize="11px" color={MUTED} lineHeight={1.8}>
            Synthetic demonstration data for a fictional pizza chain. No real advertiser, publisher or
            campaign data appears on this page. Modelled on published benchmarks:
          </Text>
          <Box as="ul" pl={5} mt={2} fontFamily="mono" fontSize="11px" color={MUTED} lineHeight={1.8}>
            {meta.sources.map((s) => <li key={s}>{s}</li>)}
            <li>
              CIMM / Go Addressable (2025): IP-to-postal accuracy 13–16% — why in-store
              conversions are reported as a floor
            </li>
          </Box>
          <Text fontFamily="mono" fontSize="11px" color={MUTED} mt={3}>
            <Text as="a" href="./modeling/" textDecoration="underline" _hover={{ color: INK }}>
              How these numbers get built →
            </Text>
            {" · "}
          </Text>
          <Text fontFamily="mono" fontSize="11px" color={MUTED} mt={1}>
            Data generated by <code>scripts/generate_madhive_data.py</code> →{" "}
            <code>public/data/madhive-campaign.json</code>, fetched at runtime. Built with React,
            TypeScript, Chakra UI and Recharts. · Sharon Kwong
          </Text>
        </Box>
      </Box>
    </Box>
  );
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <ChakraProvider theme={theme}>
      <Page />
    </ChakraProvider>
  </React.StrictMode>
);
